### ISSUE TITLE
Use relative links in README.md

### ISSUE THREAD

**Issue by ChiefArug** [ErikMcClure/bad-licenses#17]
This means that they continue to work in forked repositories and other branches.
A brief explanation of these are here: https://github.blog/2013-01-31-relative-links-in-markup-files/
It should just be a matter of making the link just the file name.

**Comment by ErikMcClure** [comment]
ya'll should stop forking my stupid joke repository and making me do work :(

fixed in https://github.com/ErikMcClure/bad-licenses/commit/e948021240eee08a5efee96f0fedd8c6a90acf6a
