### ISSUE TITLE
Remove "open-source" from github about section

### ISSUE THREAD

**Issue by soupglasses** [ErikMcClure/bad-licenses#45]
None of these licenses (at least from a quick glance) are open source according to the terms of the OSI or the FSF.

In short, my request is to change:

> A compendium of absurd open-source licenses. 

To

> A compendium of absurd software licenses.

**Comment by ErikMcClure** [comment]
I put "open-source" in quotes instead, because all these licenses *claim* to be open-source, even though almost none of them actually are.
